openapi: 3.0.0
info:
  title: Xero Accounting API
  version: 9.0.0
  description: The Xero Accounting API exposes accounting and related functions of the main Xero application
  termsOfService: https://developer.xero.com/xero-developer-platform-terms-conditions/
  contact:
    name: Xero Platform Team
    email: api@xero.com
    url: https://developer.xero.com

servers:
  - url: https://api.xero.com/api.xro/2.0
    description: Production server

security:
  - OAuth2: []

paths:
  /Contacts:
    get:
      tags:
        - Contacts
      summary: Retrieves all contacts in a Xero organisation
      operationId: getContacts
      security:
        - OAuth2:
            - accounting.contacts.read
      parameters:
        - name: xero-tenant-id
          in: header
          required: true
          description: Xero identifier for Tenant
          schema:
            type: string
            format: uuid
        - name: If-Modified-Since
          in: header
          description: Only records created or modified since this timestamp will be returned
          schema:
            type: string
            format: date-time
        - name: where
          in: query
          description: Filter by an any element
          example: 'ContactStatus=="ACTIVE"'
          schema:
            type: string
        - name: order
          in: query
          description: Order by an any element
          example: Name ASC
          schema:
            type: string
        - name: IDs
          in: query
          description: Filter by a comma separated list of ContactIDs
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              format: uuid
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: includeArchived
          in: query
          description: Include archived contacts in the response
          schema:
            type: boolean
            default: false
        - name: summaryOnly
          in: query
          description: Return summary information only
          schema:
            type: boolean
            default: false
        - name: searchTerm
          in: query
          description: Search term for contact fields
          schema:
            type: string
      responses:
        '200':
          description: Success - return response of type Contacts array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags:
        - Contacts
      summary: Creates multiple contacts (bulk) in a Xero organisation
      operationId: createContacts
      security:
        - OAuth2:
            - accounting.contacts
      parameters:
        - name: xero-tenant-id
          in: header
          required: true
          description: Xero identifier for Tenant
          schema:
            type: string
            format: uuid
        - name: summarizeErrors
          in: query
          description: If false, returns 200 OK and a mix of successfully created objects and validation errors
          schema:
            type: boolean
            default: true
        - name: Idempotency-Key
          in: header
          description: This allows you to safely retry requests without the risk of duplicate processing
          schema:
            type: string
            maxLength: 128
      requestBody:
        required: true
        description: Contacts with an array of Contact objects to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactsRequest'
      responses:
        '200':
          description: Success - return response of type Contacts array with newly created Contact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactsResponse'
        '400':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Contacts
      summary: Updates or creates one or more contacts in a Xero organisation
      operationId: updateOrCreateContacts
      security:
        - OAuth2:
            - accounting.contacts
      parameters:
        - name: xero-tenant-id
          in: header
          required: true
          description: Xero identifier for Tenant
          schema:
            type: string
            format: uuid
        - name: summarizeErrors
          in: query
          description: If false, returns 200 OK and a mix of successfully created objects and validation errors
          schema:
            type: boolean
            default: true
        - name: Idempotency-Key
          in: header
          description: This allows you to safely retry requests without the risk of duplicate processing
          schema:
            type: string
            maxLength: 128
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactsRequest'
      responses:
        '200':
          description: Success - return response of type Contacts array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactsResponse'
        '400':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          tokenUrl: https://identity.xero.com/connect/token
          scopes:
            accounting.contacts: Grants read/write access to contacts
            accounting.contacts.read: Grants read-only access to contacts

  schemas:
    ContactsRequest:
      type: object
      properties:
        Contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'

    ContactsResponse:
      type: object
      properties:
        Contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'

    Contact:
      type: object
      properties:
        ContactID:
          type: string
          format: uuid
        Name:
          type: string
        EmailAddress:
          type: string
          format: email
        ContactStatus:
          type: string

    ErrorResponse:
      type: object
      properties:
        ErrorNumber:
          type: integer
        Type:
          type: string
        Message:
          type: string
