openapi: 3.0.0
info:
  title: Xero Accounting API
  version: 9.0.0
  description: The Xero Accounting API exposes accounting and related functions of the main Xero application.
  termsOfService: https://developer.xero.com/xero-developer-platform-terms-conditions/
  contact:
    name: Xero Platform Team
    email: api@xero.com
    url: https://developer.xero.com

servers:
  - url: https://api.xero.com/api.xro/2.0

security:
  - OAuth2: []

paths:
  /Contacts:
    get:
      tags:
        - Contacts
      summary: Retrieves contacts
      operationId: getContacts
      responses:
        '200':
          description: A list of contacts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - Contacts
      summary: Creates new contacts
      operationId: createContacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactsRequest'
      responses:
        '200':
          description: Successfully created contacts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /Invoices:
    get:
      tags:
        - Invoices
      summary: Retrieves invoices
      operationId: getInvoices
      responses:
        '200':
          description: A list of invoices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoicesResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /Accounts:
    get:
      tags:
        - Accounts
      summary: Retrieves accounts
      operationId: getAccounts
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          tokenUrl: https://identity.xero.com/connect/token
          scopes:
            accounting.contacts: Grants read/write access to contacts
            accounting.contacts.read: Grants read-only access to contacts
            accounting.invoices: Grants read/write access to invoices
            accounting.invoices.read: Grants read-only access to invoices
            accounting.accounts.read: Grants read-only access to accounts

  schemas:
    ContactsRequest:
      type: object
      properties:
        Contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'

    ContactsResponse:
      type: object
      properties:
        Contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'

    Contact:
      type: object
      properties:
        ContactID:
          type: string
          format: uuid
        Name:
          type: string
        EmailAddress:
          type: string
          format: email
        ContactStatus:
          type: string

    InvoicesResponse:
      type: object
      properties:
        Invoices:
          type: array
          items:
            $ref: '#/components/schemas/Invoice'

    Invoice:
      type: object
      properties:
        InvoiceID:
          type: string
          format: uuid
        InvoiceNumber:
          type: string
        Status:
          type: string
        Contact:
          $ref: '#/components/schemas/Contact'
        Date:
          type: string
          format: date
        DueDate:
          type: string
          format: date
        LineItems:
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
        Total:
          type: number
          format: double

    LineItem:
      type: object
      properties:
        Description:
          type: string
        Quantity:
          type: number
        UnitAmount:
          type: number
        AccountCode:
          type: string

    AccountsResponse:
      type: object
      properties:
        Accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'

    Account:
      type: object
      properties:
        AccountID:
          type: string
          format: uuid
        Code:
          type: string
        Name:
          type: string
        Type:
          type: string
        Status:
          type: string

    ErrorResponse:
      type: object
      properties:
        ErrorNumber:
          type: integer
        Type:
          type: string
        Message:
          type: string
